name: cago
channels:
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.12.12=h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py39h06a4308_0
  - python=3.9.18=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2023d=h04d1e81_0
  - wheel=0.41.2=py39h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==0.15.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.10
      - aiosignal==1.3.2
      - alembic==1.14.0
      - anyio==4.1.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arm-pytorch-utilities==0.4.3
      - arrow==1.3.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - async-generator==1.10
      - async-lru==1.0.3
      - async-timeout==5.0.1
      - atari-py==0.2.9
      - attrs==23.2.0
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - cachetools==4.2.4
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - clang==5.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - comm==0.2.1
      - contextvars==2.4
      - contourpy==1.1.1
      - crafter==1.8.3
      - cycler==0.12.1
      - cython==3.0.0a10
      - dacite==1.9.2
      - dataclasses==0.6
      - datasets==3.2.0
      - debugpy==1.8.13
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.8
      - dm-control==1.0.14
      - dm-env==1.6
      - dm-tree==0.1.8
      - docopt-ng==0.9.0
      - docstring-parser==0.16
      - entrypoints==0.4
      - etils==1.5.2
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - farama-notifications==0.0.4
      - fast-kinematics==0.2.2
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - flatbuffers==1.12
      - fonttools==4.49.0
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - future==0.18.3
      - gast==0.4.0
      - gdown==5.1.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - glfw==2.6.5
      - google-auth==1.35.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - greenlet==3.1.1
      - grpcio==1.60.1
      - gym==0.15.7
      - gymnasium==0.29.1
      - gymnasium-robotics==1.2.4
      - h11==0.14.0
      - h5py==3.1.0
      - httpcore==1.0.3
      - httpx==0.26.0
      - huggingface-hub==0.27.0
      - huggingface-sb3==3.0
      - idna==3.6
      - imageio==2.34.0
      - imageio-ffmpeg==0.4.9
      - imitation==1.0.0
      - immutables==0.20
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - ipdb==0.13.13
      - ipykernel==6.29.2
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.3.2
      - json5==0.9.14
      - jsonlines==4.0.0
      - jsonpickle==4.0.1
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.0
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-widgets==3.0.10
      - keras==2.6.0
      - keras-preprocessing==1.1.2
      - keyboard==0.13.5
      - kiwisolver==1.4.5
      - labmaze==1.0.6
      - lazy-loader==0.4
      - llvmlite==0.39.1
      - lxml==5.1.0
      - mako==1.3.8
      - mani-skill==3.0.0b20
      - mani-skill2==0.5.3
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.6.3
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - metaworld==2.0.0
      - mistune==3.0.2
      - mplib==0.1.1
      - mpmath==1.3.0
      - mujoco==2.3.7
      - mujoco-py==2.1.2.14
      - multidict==6.1.0
      - multiprocess==0.70.16
      - munch==4.0.0
      - nbclassic==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.16.0
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.1.0
      - notebook-shim==0.2.4
      - numba==0.56.4
      - numpy==1.23.5
      - numpy-quaternion==2023.0.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - opencv-python==4.9.0.80
      - opensimplex==0.3
      - opt-einsum==3.3.0
      - optuna==4.1.0
      - overrides==7.7.0
      - packaging==23.2
      - pandas==1.4.4
      - pandocfilters==1.5.1
      - parso==0.8.3
      - patchelf==0.17.2.1
      - perlin-noise==1.13
      - pettingzoo==1.24.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - platformdirs==4.2.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - propcache==0.2.1
      - protobuf==3.19.6
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pygame==2.5.2
      - pyglet==1.5.0
      - pygments==2.17.2
      - pynvml==12.0.0
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pyperclip==1.9.0
      - pyquaternion==0.9.9
      - pyrsistent==0.20.0
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytorch-kinematics==0.7.5
      - pytorch-seed==0.2.0
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.33.0
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - robotics==1.2
      - rpds-py==0.18.0
      - rsa==4.9
      - rtree==1.2.0
      - ruamel-yaml==0.16.12
      - ruamel-yaml-clib==0.2.8
      - sacred==0.8.7
      - sapien==2.2.2
      - scikit-image==0.24.0
      - scikit-learn==1.4.1.post1
      - scipy==1.10.1
      - seaborn==0.12.2
      - seals==0.2.1
      - send2trash==1.8.2
      - shtab==1.7.1
      - six==1.15.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - soupsieve==2.5
      - sqlalchemy==2.0.36
      - stable-baselines3==2.4.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.6.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.6.2
      - tensorflow-estimator==2.6.0
      - tensorflow-gpu==2.6.0
      - tensorflow-probability==0.14.0
      - termcolor==1.1.0
      - terminado==0.18.0
      - testpath==0.6.0
      - threadpoolctl==3.3.0
      - tifffile==2024.8.30
      - tinycss2==1.2.1
      - toml==0.10.2
      - tomli==2.0.1
      - toppra==0.6.3
      - torch==2.6.0
      - torchaudio==2.4.1+cu124
      - torchvision==0.19.1+cu124
      - tornado==6.4
      - tqdm==4.67.1
      - traitlets==5.14.1
      - transforms3d==0.4.1
      - trimesh==4.1.4
      - triton==3.2.0
      - typeguard==4.4.2
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.13.0
      - tyro==0.9.17
      - uri-template==1.3.0
      - urllib3==2.2.0
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - wrapt==1.12.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.17.0
prefix: /anaconda3/envs/cago
